version: '3'

services:
  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  webspa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  product.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
